// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dirty30/Dirty30Pulse.tsx": () => import("../components/mockups/dirty30/Dirty30Pulse.tsx"),
  "./components/mockups/dirty30/Dirty30Velvet.tsx": () => import("../components/mockups/dirty30/Dirty30Velvet.tsx")
};
